"use client";
import { useEffect, useState } from "react";
type Recent = { id: string; winner?: string; reason?: string };
type View = { id: string; version: number; phase: string; category: string; players: { id: string; displayName: string; controller: string }[]; events: { id: number; kind: string; actorId?: string; text: string }[]; secret?: { role: string; word: string }; outcome?: { winner: string; reason: string }; revealedPlayers?: { id: string; displayName: string; role: string }[] };
export default function Home() {
 const [game, setGame] = useState<View>(); const [recent, setRecent] = useState<Recent[]>([]); const [text, setText] = useState(""); const [target, setTarget] = useState("p2"); const [error, setError] = useState("");
 async function loadRecent() { const r = await fetch("/api/games"); if (r.ok) setRecent(await r.json()); }
 useEffect(() => { void loadRecent(); }, []);
 useEffect(() => { if (game?.phase === "revealed") void loadRecent(); }, [game?.phase]);
 async function create() { const r = await fetch("/api/games", { method: "POST" }); setGame(await r.json()); setError(""); }
 async function command(action: "describe" | "question" | "answer" | "vote") { if (!game) return; const r = await fetch(`/api/games/${game.id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: crypto.randomUUID(), version: game.version, action, text, targetId: target }) }); const data = await r.json(); if (!r.ok) return setError(data.error); setGame(data); setText(""); setError(""); }
 const needsText = game?.phase === "describing" || game?.phase === "questioning";
 const action = game?.phase === "describing" ? "describe" : game?.phase === "voting" ? "vote" : game?.phase === "questioning" && game.events.at(-1)?.kind === "question" && game.events.at(-1)?.actorId !== "p1" ? "answer" : "question";
 return <main><header><p className="eyebrow">BOT OR BLUFF</p><h1>找出卧底，不要暴露你的词</h1><p>规则机器人模式 · 无需 API Key</p></header>{!game ? <><section className="card welcome"><h2>一人四席的文字猜词</h2><p>你和三位明确标识的虚构规则机器人依次描述、质疑、投票。</p><button onClick={create}>开始一局</button></section><section className="card recent" aria-label="最近十局"><h2>最近十局</h2>{recent.length ? <ol>{recent.map(item => <li key={item.id}><span>{item.winner === "civilian" ? "平民阵营获胜" : "卧底获胜"}</span><small>{item.reason}</small></li>)}</ol> : <p>完成一局后会显示在这里。</p>}</section></> : <section className="arena"><div className="card secret"><span>你的私密信息</span>{game.secret ? <><strong>{game.secret.role === "spy" ? "你是卧底" : "你是平民"}</strong><b>秘密词：{game.secret.word}</b><small>分类：{game.category}。不要直接说出秘密词。</small></> : <strong>答案已揭晓</strong>}</div><div className="card"><div className="phase"><h2>{({ describing: "描述", questioning: "质疑", voting: "投票", revealed: "揭晓" } as Record<string,string>)[game.phase]}</h2><span>第 {game.events.length} 条公开动态</span></div><ol className="chat">{game.events.map(e => <li key={e.id}><b>{e.actorId ? game.players.find(p => p.id === e.actorId)?.displayName : "裁判"}</b><span>{e.text}</span></li>)}</ol>{game.phase !== "revealed" && <div className="controls">{needsText && <textarea aria-label="输入内容" value={text} onChange={e => setText(e.target.value)} maxLength={120} placeholder={action === "answer" ? "回答机器人的问题" : "输入你的描述或问题"} />}{(action === "question" || game.phase === "voting") && <select aria-label="选择席位" value={target} onChange={e => setTarget(e.target.value)}>{game.players.filter(p => p.id !== "p1").map(p => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select>}<button onClick={() => command(action)}>{action === "describe" ? "提交描述" : action === "answer" ? "提交回答" : action === "question" ? "提问" : "确认投票"}</button></div>}{error && <p role="alert" className="error">{error}</p>}{game.phase === "revealed" && <div className="result"><h2>{game.outcome?.winner === "civilian" ? "平民阵营获胜" : "卧底获胜"}</h2><p>{game.outcome?.reason}</p>{game.revealedPlayers?.map(p => <p key={p.id}>{p.displayName}：{p.role === "spy" ? "卧底" : "平民"}</p>)}<button onClick={async () => { await loadRecent(); await create(); }}>再来一局</button></div>}</div></section>}</main>;
}
